const ERROR_CODES = Object.freeze({
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_ID: 'INVALID_ID',
    NOT_FOUND: 'NOT_FOUND',
    DUPLICATE_KEY: 'DUPLICATE_KEY',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
});

module.exports = ERROR_CODES;
